### ISSUE TITLE
app reload from route does not work

### ISSUE THREAD

**Issue by rsaccon** [David-OConnor/seed-homepage#1]
For example when doing a browser reload at `https://seed-rs.org/guide/1` it fails.

A quick look at the `index.html` source revealed, that all paths for loading assets and JS are relative. So instead of the requested resource, `index.html` gets loaded.

**Comment by David-OConnor** [comment]
Not sure how to fix. I suspect it's a server-config issue that's affecting both the dev server setup (serve.py), and the Netlify hosting this page uses. I got the live version to revert to the homepage with a server-side cfg change instead of showing an error, but it's still broken. As you observed, this only affects child paths more than 1 level down - (ie /guide isn't affected, but /guide/1 is)
